### ISSUE TITLE
Increase timeout during establishing a CAS client session

### ISSUE THREAD

**Issue by mbabadi** [cellarium-ai/cellarium-cas#62]
I have noticed that when the service is cold starting, we can get a 500 internal server error from time to time. Perhaps increasing the timeout would help?

**Comment by fedorgrab** [comment]
Just in case, I'll first take a deeper look into the nature of the error and logs. It might be smth else.

**Comment by fedorgrab** [comment]
We now have an idle instance running, which resolves this issue.
**Note:** If we decide to return to having no idle instance running, this issue should be addressed by improving the cold start time. This could be achieved by optimizing the Docker image. By making the Docker image more lightweight, it will be easier to deploy quickly.
