### ISSUE TITLE
Error with `pp.compute_most_granular_top_k_calls_single`

### ISSUE THREAD

**Issue by mdmanurung** [cellarium-ai/cellarium-cas#96]
Dear all,

Thank you releasing the model to the public.

After running `cas.annotate_matrix_cell_type_ontology_aware_strategy`, I now want to get the top-3 calls with `pp.compute_most_granular_top_k_calls_single`, however, I got the following error.

```
    322 def compute_most_granular_top_k_calls_single(
    323     adata: AnnData,
    324     cl: CellOntologyCache,
   (...)
    328     root_note: str = CL_CELL_ROOT_NODE,
    329 ):
    330     top_k_calls_dict = defaultdict(list)
--> 331     scores_array_nc = adata.obsm[CAS_CL_SCORES_ANNDATA_OBSM_KEY].toarray()
    333     # make a wrapped aggregated scores dataclass for the single cell in question
    334     aggregated_scores = AggregatedCellOntologyScores(
    335         aggregation_op=CellOntologyScoresAggregationOp.MEAN,
    336         aggregation_domain=CellOntologyScoresAggregationDomain.ALL_CELLS,
   (...)
    353         cl_names=cl.cl_names,
    354     )
```

It seems the error originate at line 331, where the function tries to look for a new `.obsm` key. The thing is, I cannot find it in my anndata object. How can I solve this?

Thanks in advance for your kind help.

Regards,
Mikhael

**Comment by mbabadi** [comment]
Hi Mickael,

You need to insert the CAS output into the AnnData file before calling `compute_most_granular_top_k_calls_single`.  Assuming that the output object you get from CAS is `cas_ontology_aware_response` and your AnnData object is `adata`, you would need to perform the following operations:

```
from cellarium.cas.postprocessing import insert_cas_ontology_aware_response_into_adata

insert_cas_ontology_aware_response_into_adata(cas_ontology_aware_response, adata)
```

Let me know if this resolves the issue. This step was included in the Quickstart tutorial within the section that initiates the interactive Dash App, with the assumption that users would proceed through the tutorial in order. Based on your feedback, I can update the tutorial to emphasize this step more clearly.

Best,
Mehrtash

**Comment by mdmanurung** [comment]
Hi Mehrtash,

Thank you for the clarification! Considering that my main interest was to compare CAS' results with my pre-existing annotation, I skipped the exploration step. I imagine many people would have similar ideas.

Regards,
Mikhael
